channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - catboost==1.2.7
  - cloudpickle==3.1.0
  - ipywidgets==8.1.5
  - numpy==1.26.4
  - pandas==2.2.3
  - psutil==6.1.1
  - scikit-learn==1.6.1
  - scipy==1.15.0
  - xgboost==2.1.3
name: mlflow-env
